env = Environment(CPPPATH = ["."])
#env.Append(CXXFLAGS=["/std:c++20", "/Od", "/Zi", "/DEBUG", "/EHsc"])
env.Append(CXXFLAGS=["/std:c++20", "/Ox", "/EHsc"])

env.Append(LINKFLAGS=['/SUBSYSTEM:WINDOWS'])
env.Append(LIBS=["user32"])
env.Program("volumehotkey", Glob("*.cpp"))